<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ContractDefinition" nsURI="https://www.example.org/contractDef"
    nsPrefix="ContractDefinition">
  <eClassifiers xsi:type="ecore:EClass" name="ContractDefinition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContractType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" upperBound="-1"
        eType="#//ObjectDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="#//ObjectDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContractType">
    <eLiterals name="PRECONDITION"/>
    <eLiterals name="POSTCONDITION" value="1"/>
    <eLiterals name="INVARIANT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionDef" eSuperTypes="#//ContractDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thendefinition" lowerBound="1"
        upperBound="-1" eType="#//ThenDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifdefinition" lowerBound="1"
        upperBound="-1" eType="#//IfDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeDefinition" abstract="true" eSuperTypes="#//ContractDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thendefinition" lowerBound="1"
        eType="#//ThenDefinition" eOpposite="#//ThenDefinition/ifdefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataCondition" lowerBound="1"
        upperBound="-1" eType="#//ValueDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifdefinition" lowerBound="1"
        eType="#//IfDefinition" eOpposite="#//IfDefinition/thendefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataResult" lowerBound="1"
        eType="#//ValueDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueRangeDefinition" eSuperTypes="#//RangeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuedefinition" lowerBound="1"
        upperBound="-1" eType="#//ValueDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//ValueRange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldRangeDefinition" eSuperTypes="#//RangeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//FieldRange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectDefinition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataDictionaryDef" eSuperTypes="#//ObjectDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//DataDictionary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFieldDef" eSuperTypes="#//ObjectDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//DataField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueDefinition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quantitydef" eType="#//QuantityDef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixValueDef" eSuperTypes="#//OperandDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//FixValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//Interval"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantityDef" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PercentDef" eSuperTypes="#//QuantityDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//Percent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteValueDef" eSuperTypes="#//QuantityDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//AbsoluteValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedValueDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//DerivedValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumOpDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//NumOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialValueDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//SpecialValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathOpDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operanddef" lowerBound="2"
        upperBound="2" eType="#//OperandDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//MathOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CastTypeDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//CastType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperandDef" abstract="true" eSuperTypes="#//ValueDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//Join"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operanddef" lowerBound="1"
        upperBound="-1" eType="#//OperandDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpFieldDef" eSuperTypes="#//OperandDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//OpField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateIntervalDef" eSuperTypes="#//ValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundTo" eType="ecore:EClass Contract.ecore#//DateInterval"/>
  </eClassifiers>
</ecore:EPackage>
